newmovies/newmovies/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('trialapp.urls'))
]

newmovies/trialapp/urls.py
from django.conf.urls.static import static
from django.urls import path

from newmovies import settings
from .import views
app_name = 'movieapp'

urlpatterns = [

    path('',views.data,name='data'),
    path('movie/<int:uniq_id>/',views.main,name='main'),
    path('add/',views.insert,name='insert'),
    path('update/<int:uid>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

newmovies/trialapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='pics')
    def __str__(self):
        return self.name

newmovies/trialapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movies
from .form import Newform


# Create your views here.
def data(request):
    movie = movies.objects.all()
    return render(request,'index.html',{'key':movie})
def main(request,uniq_id):
    page = movies.objects.get(id=uniq_id)
    return render(request,'main.html',{'pas':page})
def insert(request):
    if request.method == "POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        order = movies(name=name,desc=desc,year=year,img=img)
        order.save()
    return render(request,'insert.html')

def update(request,uid):
    movie = movies.objects.get(id=uid)
    form = Newform(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'movie':movie,'form':form})

def delete(request,id):
    if request.method == 'POST':
        movie = movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

newmovies/templates/base.html
{% load static %}
<html>
<head>
    <title>front</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" style="color:red;" >Movie store</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

newmovies/templates/delete.html
<form method="post">
  {% csrf_token %}
  Are you sure you want to delete the movie?<br>
  <input type="submit">
</form>

newmovies/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in key %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200" height="200">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text"></p>
    <a href="{% url 'movieapp:main' i.id %}" class="btn btn-primary">See more</a>
  </div>
</div>
        </div>
        {% endfor %}

    </div>
</div>


<center>
<a class="btn btn-warning" href="{% url 'movieapp:insert'  %}">Add Movie</a>

</center>
{% endblock %}

newmovies/templates/insert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    <center>
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br>
    <input type="text" name="desc" placeholder="Enter movie description"><br>
    <input type="text" name="year" placeholder="Enter movie year"><br>
    <input type="file" name="img"><br>
    <input type="submit">
    </center>
</form>
{% endblock %}
</body>
</html>

newmovies/templates/main.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <img src="{{pas.img.url}}" height="300" width="300">
        <div class="col-md-6">
            <h2>{{pas.name}} ({{pas.year}})</h2>
            <h5>{{pas.desc}}</h5>
            <a class="btn btn-warning" href="{% url 'movieapp:update' pas.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete'  pas.id %}">Delete</a>
        </div>

    </div>
</div>


{% endblock %}

newmovies/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
        {{form.as_p }}
    <input type="submit">

</form>

</body>
</html>